### ISSUE TITLE
[Request] Allow Multiple Webhook Urls

### ISSUE THREAD

**Issue by Nick2bad4u** [PJGJ210/Discord-Collection-Logger#4]
Would like to be able to post in multiple channels/discords

**Comment by PJGJ210** [comment]
Solution to just set as comma delimited webhooks and iterate each. I'll
check on this sometime soon...should be simple enough. If any pulls come
through ill check em.

**Comment by OrenWiesz** [comment]
hello, was wondering if it was added yet
if so, putting webhook1 , webhook 2
should do the trick?

**Comment by PJGJ210** [comment]
Just looked at this one. Got a bit distracted and fell off. 

https://github.com/runelite/plugin-hub/pull/4494

pending runelite update now
