### ISSUE TITLE
Config import to Dink

### ISSUE THREAD

**Issue by iProdigy** [PJGJ210/Discord-Collection-Logger#5]
Hi Paul!

In [Dink](https://github.com/pajlads/DinkPlugin) we're adding a command that allows users to import settings from other Discord webhook plugins.
A maintainer of another webhook plugin suggested we implement this feature to handle their plugin.

We are currently working on adding support for your plugin; would you have any questions or objections?

**Comment by PJGJ210** [comment]
@iProdigy 
Feel free. I often point people toward Dink as well should they have other requirements. 

Let me know if you need any assistance on my end.

**Comment by iProdigy** [comment]
Thanks! I'll reach out if anything comes up
